### ISSUE TITLE
Run the generator on this project

### ISSUE THREAD

**Issue by BioBoost** [vives-devbit/git-course#2]
Run the generator on this project. It will also fix zooming and the missing home link.

**Comment by pcordemans** [comment]
I'll buy you a bicky it this doesn't blow up the site

**Comment by BioBoost** [comment]
Shit man I branch :)

**Comment by sillevl** [comment]
![](http://www.reactiongifs.com/wp-content/uploads/2011/05/MichealJacksonPopcorn.gif)
